// GENERATED by scripts/build-compose-widgets.js from the widget folders - do not edit.
(function () {
  const register = window.DashCompose.registerWidget;
  // --- bar
  register({"type":"bar","version":1,"renderer":"dom","name":{"en":"Bar","hu":"Sáv","de":"Balken"},"defaultSize":{"w":4,"h":2},"minSize":{"w":2,"h":1},"binds":[{"key":"value","kinds":["number"],"name":{"en":"Value","hu":"Érték","de":"Wert"},"default":"batteryPercent"}],"props":[{"key":"label","type":"string","default":"","name":{"en":"Label","hu":"Felirat","de":"Beschriftung"}},{"key":"showLabel","type":"bool","default":true,"name":{"en":"Show label","hu":"Felirat mutatása","de":"Beschriftung anzeigen"}},{"key":"min","type":"number","default":null,"name":{"en":"Minimum","hu":"Minimum","de":"Minimum"}},{"key":"max","type":"number","default":null,"name":{"en":"Maximum","hu":"Maximum","de":"Maximum"}},{"key":"precision","type":"number","default":null,"min":0,"max":3,"name":{"en":"Decimals","hu":"Tizedesjegyek","de":"Nachkommastellen"}},{"key":"accent","type":"color","default":"","name":{"en":"Bar color","hu":"Sáv színe","de":"Balkenfarbe"}},{"key":"showValue","type":"bool","default":true,"name":{"en":"Show value","hu":"Érték mutatása","de":"Wert anzeigen"}}]}, (function () {
    // Horizontal bar. Ranges that cross zero (power: regen vs. discharge) fill
    // from the zero point outwards. One transform write per visible change.
    function create(ctx) {
      const { el, props } = ctx;
      if (props.accent) el.style.setProperty("--accent", props.accent);

      const head = document.createElement("div");
      head.className = "bar__head";
      if (props.showLabel) {
        const label = document.createElement("span");
        label.className = "bar__label";
        label.textContent = props.label || ctx.label("value");
        head.appendChild(label);
      }

      let text = null;
      if (props.showValue) {
        const value = document.createElement("span");
        value.className = "bar__value";
        text = document.createTextNode("");
        const unit = document.createElement("span");
        unit.className = "bar__unit";
        unit.textContent = ctx.unit("value");
        value.append(text, unit);
        head.appendChild(value);
        el.style.setProperty("--unit-chars", unit.textContent.length);
      }

      const track = document.createElement("div");
      track.className = "bar__track";
      const fill = document.createElement("div");
      fill.className = "bar__fill";
      track.appendChild(fill);
      if (head.firstChild) el.append(head);
      else el.dataset.bare = "1";
      el.append(track);

      function bounds() {
        const range = ctx.range("value") || [0, 100];
        const min = props.min ?? range[0];
        const max = props.max ?? range[1];
        return max > min ? [min, max] : [0, 1];
      }

      const ratio = (v, [min, max]) => Math.min(1, Math.max(0, (v - min) / (max - min)));
      // 0.2 % steps: finer changes are invisible and would only cost writes.
      const quantize = (r) => Math.round(r * 500) / 500;

      let lastText = null, lastLength = -1;
      let lastTransform = null;
      return {
        update(values) {
          const v = values.value;
          if (text) {
            const next = ctx.format("value", v, props.precision ?? undefined);
            if (next !== lastText) {
              lastText = next;
              text.nodeValue = next;
              if (next.length !== lastLength) {
                lastLength = next.length;
                el.style.setProperty("--chars", next.length);
              }
            }
          }
          const b = bounds();
          let start = 0, end = 0;
          if (v !== undefined) {
            const zero = ratio(0, b);
            const at = ratio(v, b);
            start = quantize(Math.min(zero, at));
            end = quantize(Math.max(zero, at));
          }
          const transform = "translateX(" + start * 100 + "%) scaleX(" + (end - start) + ")";
          if (transform !== lastTransform) {
            lastTransform = transform;
            fill.style.transform = transform;
          }
        },
      };
    }
    return create;
  })());
  // --- lamp
  register({"type":"lamp","version":1,"renderer":"dom","name":{"en":"Indicator","hu":"Jelzőfény","de":"Kontrollleuchte"},"defaultSize":{"w":2,"h":2},"minSize":{"w":1,"h":1},"binds":[{"key":"value","kinds":["bool"],"name":{"en":"Condition","hu":"Feltétel","de":"Bedingung"},"default":"adasOn"},{"key":"angle","kinds":["number"],"default":null,"name":{"en":"Rotate by","hu":"Forgatás ennyivel","de":"Drehen um"}}],"props":[{"key":"label","type":"string","default":"","name":{"en":"Label","hu":"Felirat","de":"Beschriftung"}},{"key":"icon","type":"enum","default":"dot","options":["dot","arrow-left","arrow-right","warning","wheel"],"name":{"en":"Icon","hu":"Ikon","de":"Symbol"}},{"key":"color","type":"color","default":"#22c55e","name":{"en":"Active color","hu":"Aktív szín","de":"Aktive Farbe"}},{"key":"blink","type":"bool","default":false,"name":{"en":"Blink when active","hu":"Villogjon aktívan","de":"Blinken wenn aktiv"}},{"key":"hideWhenOff","type":"bool","default":false,"name":{"en":"Hide when off","hu":"Rejtve, ha nem aktív","de":"Ausblenden wenn aus"}},{"key":"showLabel","type":"bool","default":false,"name":{"en":"Show label","hu":"Felirat mutatása","de":"Beschriftung anzeigen"}}]}, (function () {
    // On/off indicator for any bool signal. The whole visual state is one
    // data-on attribute on the cell body; colors and blinking live in CSS.
    function create(ctx) {
      const { el, props } = ctx;
      const ICONS = {
        dot: '<circle cx="12" cy="12" r="7"/>',
        "arrow-left": '<path d="M10 4 2 12l8 8v-5h12V9H10z"/>',
        "arrow-right": '<path d="m14 4 8 8-8 8v-5H2V9h12z"/>',
        warning: '<path d="M12 2 1 21h22L12 2zm-1 7h2v6h-2V9zm0 8h2v2h-2v-2z"/>',
        wheel: '<path d="M12 2a10 10 0 1 0 0 20 10 10 0 0 0 0-20zm0 3a7 7 0 0 1 6.9 6h-3.2a3.8 3.8 0 0 0-7.4 0H5.1A7 7 0 0 1 12 5zm-6.9 8h3.3a4 4 0 0 0 2.6 2.6v3.3A7 7 0 0 1 5.1 13zm7.9 5.9v-3.3a4 4 0 0 0 2.6-2.6h3.3a7 7 0 0 1-5.9 5.9z"/>',
      };

      el.style.setProperty("--lamp-on", props.color);
      el.dataset.on = "0";
      if (props.blink) el.dataset.blink = "1";
      if (props.hideWhenOff) el.dataset.hideOff = "1";

      const icon = document.createElementNS("http://www.w3.org/2000/svg", "svg");
      icon.setAttribute("viewBox", "0 0 24 24");
      icon.setAttribute("class", "lamp__icon");
      icon.setAttribute("aria-hidden", "true");
      icon.innerHTML = ICONS[props.icon] || ICONS.dot;
      el.appendChild(icon);

      if (props.showLabel) {
        const label = document.createElement("div");
        label.className = "lamp__label";
        label.textContent = props.label || ctx.label("value");
        el.appendChild(label);
      }

      let last = "0";
      let lastAngle = 0;
      return {
        update(values) {
          const next = values.value ? "1" : "0";
          if (next !== last) {
            last = next;
            el.dataset.on = next;
          }
          // Optional: turn the icon by a signal (degrees), e.g. the wheel by the steering angle.
          if (values.angle !== undefined && !el.dataset.rotate) el.dataset.rotate = "1";
          const angle = values.angle === undefined ? 0 : Math.round(values.angle);
          if (angle !== lastAngle) {
            lastAngle = angle;
            icon.style.transform = angle ? "rotate(" + angle + "deg)" : "";
          }
        },
      };
    }
    return create;
  })());
  // --- power
  register({"type":"power","version":1,"renderer":"dom","name":{"en":"Power bar","hu":"Teljesítménysáv","de":"Leistungsbalken"},"defaultSize":{"w":1,"h":3},"minSize":{"w":1,"h":1},"binds":[{"key":"value","kinds":["number"],"name":{"en":"Power","hu":"Teljesítmény","de":"Leistung"},"default":"powerLevel"}],"props":[{"key":"label","type":"string","default":"","name":{"en":"Label","hu":"Felirat","de":"Beschriftung"}},{"key":"showLabel","type":"bool","default":false,"name":{"en":"Show label","hu":"Felirat mutatása","de":"Beschriftung anzeigen"}},{"key":"showValue","type":"bool","default":false,"name":{"en":"Show value","hu":"Érték mutatása","de":"Wert anzeigen"}},{"key":"regenColor","type":"color","default":"","name":{"en":"Regen color","hu":"Visszatáplálás színe","de":"Rekuperationsfarbe"}},{"key":"driveColor","type":"color","default":"","name":{"en":"Discharge color","hu":"Leadás színe","de":"Entladungsfarbe"}}]}, (function () {
    // Regen / discharge bar as in web-vanilla: zero in the middle, fed a signed
    // -100..100 level. Orientation follows the cell shape (CSS), JS only writes --start / --len.
    function create(ctx) {
      const { el, props } = ctx;
      if (props.regenColor) el.style.setProperty("--regen", props.regenColor);
      if (props.driveColor) el.style.setProperty("--drive", props.driveColor);

      let text = null;
      if (props.showLabel || props.showValue) {
        const head = document.createElement("div");
        head.className = "power__head";
        if (props.showLabel) {
          const label = document.createElement("span");
          label.className = "power__label";
          label.textContent = props.label || ctx.label("value");
          head.appendChild(label);
        }
        if (props.showValue) {
          const value = document.createElement("span");
          value.className = "power__value";
          text = document.createTextNode("");
          const unit = document.createElement("span");
          unit.className = "power__unit";
          unit.textContent = ctx.unit("value");
          value.append(text, unit);
          head.appendChild(value);
        }
        el.appendChild(head);
      }

      const track = document.createElement("div");
      track.className = "power__track";
      const center = document.createElement("div");
      center.className = "power__center";
      const fill = document.createElement("div");
      fill.className = "power__fill";
      track.append(fill, center);
      el.appendChild(track);

      const quantize = (r) => Math.round(r * 500) / 500;

      function span(v) {
        const half = Math.min(1, Math.abs(v) / 100) * 0.5;
        return v < 0 ? [0.5 - half, 0.5] : [0.5, 0.5 + half];
      }

      let lastText = null, lastStart = null, lastLen = null, lastRegen = null;
      return {
        update(values) {
          const v = values.value;
          if (text) {
            const next = ctx.format("value", v, undefined);
            if (next !== lastText) {
              lastText = next;
              text.nodeValue = next;
            }
          }
          const [a, b] = v === undefined ? [0.5, 0.5] : span(v);
          const start = quantize(a), len = quantize(b - a);
          if (start !== lastStart) {
            lastStart = start;
            el.style.setProperty("--start", start);
          }
          if (len !== lastLen) {
            lastLen = len;
            el.style.setProperty("--len", len);
          }
          const regen = v < 0 ? "1" : "0";
          if (regen !== lastRegen) {
            lastRegen = regen;
            el.dataset.regen = regen;
          }
        },
      };
    }
    return create;
  })());
  // --- radial
  register({"type":"radial","version":1,"renderer":"svg","name":{"en":"Radial gauge","hu":"Kör műszer","de":"Rundinstrument"},"defaultSize":{"w":4,"h":4},"minSize":{"w":2,"h":2},"binds":[{"key":"value","kinds":["number"],"name":{"en":"Value","hu":"Érték","de":"Wert"},"default":"egoSpeed"},{"key":"marker","kinds":["number"],"default":null,"name":{"en":"Marker","hu":"Jelölő","de":"Markierung"}}],"props":[{"key":"label","type":"string","default":"","name":{"en":"Label","hu":"Felirat","de":"Beschriftung"}},{"key":"min","type":"number","default":null,"name":{"en":"Minimum","hu":"Minimum","de":"Minimum"}},{"key":"max","type":"number","default":null,"name":{"en":"Maximum","hu":"Maximum","de":"Maximum"}},{"key":"precision","type":"number","default":null,"min":0,"max":3,"name":{"en":"Decimals","hu":"Tizedesjegyek","de":"Nachkommastellen"}},{"key":"accent","type":"color","default":"","name":{"en":"Arc color","hu":"Ív színe","de":"Bogenfarbe"}},{"key":"showLabel","type":"bool","default":true,"name":{"en":"Show label","hu":"Felirat mutatása","de":"Beschriftung anzeigen"}}]}, (function () {
    // 270° arc gauge in a 200×200 viewBox; the SVG scales to any square-ish cell.
    // The value arc uses pathLength=100, so progress is a single dashoffset write.
    function create(ctx) {
      const { el, props } = ctx;
      const NS = "http://www.w3.org/2000/svg";
      const CX = 100, CY = 100, R = 82;
      const START = 135, SWEEP = 270;

      if (props.accent) el.style.setProperty("--accent", props.accent);

      function point(deg, r) {
        const a = (deg * Math.PI) / 180;
        return [CX + r * Math.cos(a), CY + r * Math.sin(a)];
      }
      function arcPath(r) {
        const [x0, y0] = point(START, r);
        const [x1, y1] = point(START + SWEEP, r);
        return "M" + x0.toFixed(2) + " " + y0.toFixed(2) + " A" + r + " " + r + " 0 1 1 " + x1.toFixed(2) + " " + y1.toFixed(2);
      }
      function node(name, attrs) {
        const n = document.createElementNS(NS, name);
        for (const k in attrs) n.setAttribute(k, attrs[k]);
        return n;
      }

      const svg = node("svg", { viewBox: "0 0 200 200", class: "radial__svg", "aria-hidden": "true" });
      svg.appendChild(node("path", { d: arcPath(R), class: "radial__track", pathLength: "100" }));
      const arc = node("path", { d: arcPath(R), class: "radial__arc", pathLength: "100", "stroke-dasharray": "100 100", "stroke-dashoffset": "100" });
      svg.appendChild(arc);

      const markerGroup = node("g", { class: "radial__marker", visibility: "hidden" });
      const [mx0, my0] = point(0, R - 16);
      const [mx1, my1] = point(0, R + 16);
      markerGroup.appendChild(node("line", { x1: mx0, y1: my0, x2: mx1, y2: my1 }));
      svg.appendChild(markerGroup);

      const valueText = node("text", { x: CX, y: CY + 12, class: "radial__value", "text-anchor": "middle" });
      const valueNode = document.createTextNode("");
      valueText.appendChild(valueNode);
      svg.appendChild(valueText);

      const unitText = node("text", { x: CX, y: CY + 44, class: "radial__unit", "text-anchor": "middle" });
      unitText.textContent = ctx.unit("value");
      svg.appendChild(unitText);

      if (props.showLabel) {
        const labelText = node("text", { x: CX, y: CY - 40, class: "radial__label", "text-anchor": "middle" });
        labelText.textContent = props.label || ctx.label("value");
        svg.appendChild(labelText);
      }
      el.appendChild(svg);

      function bounds() {
        const range = ctx.range("value") || [0, 100];
        const min = props.min ?? range[0];
        const max = props.max ?? range[1];
        return max > min ? [min, max] : [0, 1];
      }
      const ratio = (v, [min, max]) => Math.min(1, Math.max(0, (v - min) / (max - min)));

      let lastText = null, lastOffset = null, lastMarker = null, lastVisibility = "hidden", lastArcVisible = true;
      return {
        update(values) {
          const b = bounds();
          const text = ctx.format("value", values.value, props.precision ?? undefined);
          if (text !== lastText) {
            lastText = text;
            valueNode.nodeValue = text;
          }
          // Half-percent steps: finer arc changes are not visible.
          const offset = values.value === undefined ? 100 : Math.round((1 - ratio(values.value, b)) * 200) / 2;
          if (offset !== lastOffset) {
            // A round cap paints a dot even at zero length, so hide the arc there.
            const visible = offset < 100;
            if (visible !== lastArcVisible) {
              lastArcVisible = visible;
              arc.setAttribute("visibility", visible ? "visible" : "hidden");
            }
            lastOffset = offset;
            arc.setAttribute("stroke-dashoffset", offset);
          }
          const m = values.marker;
          const marker = m === undefined || m <= 0 ? "" : "rotate(" + (START + SWEEP * ratio(m, b)).toFixed(1) + " " + CX + " " + CY + ")";
          if (marker !== lastMarker) {
            lastMarker = marker;
            if (marker) markerGroup.setAttribute("transform", marker);
            const visibility = marker ? "visible" : "hidden";
            if (visibility !== lastVisibility) {
              lastVisibility = visibility;
              markerGroup.setAttribute("visibility", visibility);
            }
          }
        },
      };
    }
    return create;
  })());
  // --- readout
  register({"type":"readout","version":1,"renderer":"dom","name":{"en":"Readout","hu":"Kijelző","de":"Anzeige"},"defaultSize":{"w":3,"h":2},"minSize":{"w":2,"h":1},"binds":[{"key":"value","kinds":["number","enum","string"],"name":{"en":"Value","hu":"Érték","de":"Wert"},"default":"egoSpeed"}],"props":[{"key":"label","type":"string","default":"","name":{"en":"Label","hu":"Felirat","de":"Beschriftung"}},{"key":"showLabel","type":"bool","default":true,"name":{"en":"Show label","hu":"Felirat mutatása","de":"Beschriftung anzeigen"}},{"key":"precision","type":"number","default":null,"min":0,"max":3,"name":{"en":"Decimals","hu":"Tizedesjegyek","de":"Nachkommastellen"}},{"key":"accent","type":"color","default":"","name":{"en":"Value color","hu":"Érték színe","de":"Wertfarbe"}},{"key":"align","type":"enum","default":"start","options":["start","center","end"],"name":{"en":"Alignment","hu":"Igazítás","de":"Ausrichtung"}}]}, (function () {
    // Label, big value, unit. Layout adapts to the cell through container queries
    // in widget.css; this file only writes the value text.
    function create(ctx) {
      const { el, props } = ctx;
      el.dataset.align = props.align;
      if (props.accent) el.style.setProperty("--accent", props.accent);

      let label = null;
      if (props.showLabel) {
        label = document.createElement("div");
        label.className = "readout__label";
        label.textContent = props.label || ctx.label("value");
      } else {
        el.dataset.bare = "1";
      }

      const line = document.createElement("div");
      line.className = "readout__line";
      const value = document.createElement("span");
      value.className = "readout__value";
      const text = document.createTextNode("");
      value.appendChild(text);
      const unit = document.createElement("span");
      unit.className = "readout__unit";
      unit.textContent = ctx.unit("value");
      line.append(value, unit);

      if (label) el.append(label);
      el.append(line);
      el.style.setProperty("--unit-chars", unit.textContent.length);

      // --chars drives the font size in widget.css so long values (odometer) fit.
      // It changes only when the text length does, not every tick.
      let last = null, lastLength = -1;
      return {
        update(values) {
          const next = ctx.format("value", values.value, props.precision ?? undefined);
          if (next === last) return;
          last = next;
          text.nodeValue = next;
          if (next.length !== lastLength) {
            lastLength = next.length;
            el.style.setProperty("--chars", next.length);
          }
        },
      };
    }
    return create;
  })());
})();
